name: Send submodule updates to huynguyen-blog-build Repo Stage Branch

on:
  push:
    branches: 
      - draft

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with: 
          repository: sinicide/huynguyen-blog-build
          ref: stage
          token: ${{ secrets.PRIVATE_TOKEN_GITHUB }}
          submodules: true
          fetch-depth: 0

      - name: Pull & update submodules
        run: |
          git submodule update --remote

      - name: Commit
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions - update submodules"
          git add .
          git commit -m "Update submodules" || echo "No changes to commit"
          git push